root: "/var/www/vhosts"
git-wrapper:
  git-binary:
  env-vars:
virtual-hosts:
  default:
    index:
      exclude:
        - "git-checker"
        - "lost+found"
    show:
      depth: "< 4"
      exclude:
    add:
      allow:
      exclude:
    umask:
      file:
      folder:
